import {
  Activity,
  Braces,
  Briefcase,
  Camera,
  Code,
  Compass,
  Cpu,
  Database,
  FileSpreadsheet,
  FileText,
  Globe,
  Layers,
  LayoutTemplate,
  Link2,
  ListChecks,
  Megaphone,
  Monitor,
  MonitorSmartphone,
  Search,
  SearchCheck,
  Server,
  Share2,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Wrench,
} from "lucide-react";

// Icons you can use by name in src/data/portfolio.js.
// To add one: import it above from "lucide-react" and list it here.
const icons = {
  Activity,
  Braces,
  Briefcase,
  Camera,
  Code,
  Compass,
  Cpu,
  Database,
  FileSpreadsheet,
  FileText,
  Globe,
  Layers,
  LayoutTemplate,
  Link2,
  ListChecks,
  Megaphone,
  Monitor,
  MonitorSmartphone,
  Search,
  SearchCheck,
  Server,
  Share2,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Wrench,
};

export default function Icon({ name, ...props }) {
  const Component = icons[name] ?? Code;
  return <Component aria-hidden="true" {...props} />;
}
